{{- range .Values.tenants }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  labels:
    {{- include "k8s-ref-demo.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
    app: {{ .name }}
spec:
  selector:
    app: {{ .name }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 9797
      targetPort: metrics
      protocol: TCP
{{- end }}
