{{- if .Values.eso.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tenant-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "k8s-ref-demo.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: k8s-ref-demo-store
    kind: ClusterSecretStore
  target:
    name: tenant-config
    creationPolicy: Owner
  data:
    - secretKey: app-env
      remoteRef:
        key: eso-source-config
        property: app-env
    - secretKey: feature-flags
      remoteRef:
        key: eso-source-config
        property: feature-flags
    - secretKey: log-level
      remoteRef:
        key: eso-source-config
        property: log-level
{{- end }}
